# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CosoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coso',
            old_name='nombre',
            new_name='nombreCoso',
        ),
    ]
